//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string CompanyURl { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public string NTN { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string logo { get; set; }
        public string Currency { get; set; }
        public string SNTN { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
