//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int CustomerOrderID { get; set; }
        public string Address { get; set; }
        public string NearestPlace { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string ContactNo { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PlaceType { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string Email { get; set; }
        public string CardNotes { get; set; }
        public string SelectedTime { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string SenderContact { get; set; }
        public string CouponCode { get; set; }
        public Nullable<int> ShippingStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
    }
}
