//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsCategory
    {
        public int ID { get; set; }
        public Nullable<int> DealID { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Count { get; set; }
        public Nullable<double> CategoryID { get; set; }
        public Nullable<double> CatName { get; set; }
    
        public virtual DealsHeader DealsHeader { get; set; }
    }
}
