//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealsHeader()
        {
            this.DealsCategories = new HashSet<DealsCategory>();
            this.DealsDetails = new HashSet<DealsDetail>();
        }
    
        public int ID { get; set; }
        public string DealNo { get; set; }
        public Nullable<double> DealPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DealType { get; set; }
        public Nullable<int> ItemsCount { get; set; }
        public string DealName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<double> DealCost { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealsCategory> DealsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealsDetail> DealsDetails { get; set; }
        public virtual Location Location { get; set; }
    }
}
