//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueStockDetail
    {
        public int ID { get; set; }
        public Nullable<int> IssueStockID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Name { get; set; }
        public Nullable<double> IssueQty { get; set; }
        public Nullable<double> RequestQty { get; set; }
        public Nullable<double> ReceiveQty { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual IssueStock IssueStock { get; set; }
        public virtual Item Item { get; set; }
    }
}
