//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImage
    {
        public int ItemImagesID { get; set; }
        public string Image { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
