//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<double> CashPayment { get; set; }
        public Nullable<double> CardPayment { get; set; }
        public Nullable<double> CreditPayment { get; set; }
        public string PaymentType { get; set; }
        public string CardType { get; set; }
        public Nullable<double> Total { get; set; }
        public string CardNumber { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
