//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPermission
    {
        public int ReceiptID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> IsLogo { get; set; }
        public Nullable<bool> IsLocationName { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsRegistrationNo { get; set; }
        public Nullable<bool> IsTaxID { get; set; }
        public Nullable<bool> IsOrderNo { get; set; }
        public Nullable<bool> IsFooter { get; set; }
        public Nullable<bool> IsContact { get; set; }
        public Nullable<bool> IsAddress { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsKitchenReceipt { get; set; }
        public string FooterNotes { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Snapchat { get; set; }
        public string Twitter { get; set; }
        public string OrderNoPrefix { get; set; }
    
        public virtual User User { get; set; }
    }
}
